apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hiresphere-project
  namespace: argocd
spec:
  description: HireSphere production deployment
  sourceRepos:
    - https://github.com/rahultiple31/hiresphere.git
  destinations:
    - namespace: hiresphere
      server: https://kubernetes.default.svc
    - namespace: hiresphere-gateway
      server: https://kubernetes.default.svc
    - namespace: hiresphere-api
      server: https://kubernetes.default.svc
    - namespace: hiresphere-workspace
      server: https://kubernetes.default.svc
    - namespace: hiresphere-jobs
      server: https://kubernetes.default.svc
    - namespace: hiresphere-projects
      server: https://kubernetes.default.svc
    - namespace: hiresphere-network
      server: https://kubernetes.default.svc
    - namespace: hiresphere-interview
      server: https://kubernetes.default.svc
    - namespace: hiresphere-profile
      server: https://kubernetes.default.svc
    - namespace: hiresphere-hr-studio
      server: https://kubernetes.default.svc
    - namespace: hiresphere-scale
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: Service
    - group: ''
      kind: Secret
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: networking.k8s.io
      kind: Ingress
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: Ingress
