apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "network.fullname" . }}
  labels:
    {{- include "network.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "network.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "network.labels" . | nindent 8 }}
    spec:
      containers:
        - name: network
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
