apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobs
  namespace: argocd
spec:
  project: hiresphere-project
  source:
    repoURL: https://github.com/your-org/hiresphere.git
    targetRevision: main
    path: charts/jobs
  destination:
    server: https://kubernetes.default.svc
    namespace: hiresphere-jobs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
