apiVersion: v1
kind: Service
metadata:
  name: {{ include "hiresphere.fullname" . }}
  labels:
    {{- include "hiresphere.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "hiresphere.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
{{ range .Values.microservices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
  labels:
    {{- include "hiresphere.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hiresphere.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
{{ end }}
