name: HireSphere CI/CD

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  APP_DIR: .
  CHART_PATH: charts/hiresphere
  IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}/hiresphere
  DOCKERHUB_REPOSITORY: rahultipledocker/hiresphere
  RELEASE_NAME: hiresphere
  KUBE_NAMESPACE: hiresphere

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - run: |

        test -f index.html
        test -f styles.css
        test -f app.js
        test -f Dockerfile
        test -f nginx.conf

    - uses: azure/setup-helm@v4

    - run: helm lint $CHART_PATH

  image:

    needs: validate

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.IMAGE_REPOSITORY }}
          ${{ env.DOCKERHUB_REPOSITORY }}

        tags: |
          type=sha,prefix=sha-
          type=raw,value=latest
          type=raw,value=1.0

    - uses: docker/build-push-action@v6

      with:

        context: .

        file: ./Dockerfile

        platforms: linux/amd64,linux/arm64

        push: ${{ github.event_name != 'pull_request' }}

        tags: ${{ steps.meta.outputs.tags }}

        labels: ${{ steps.meta.outputs.labels }}

        cache-from: type=gha

        cache-to: type=gha,mode=max

    - name: Test image

      run: |

        docker run -d \
        --name app \
        -p 8080:8080 \
        rahultipledocker/hiresphere:1.0

        sleep 10

        curl localhost:8080/healthz
